source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'mysql2'
gem 'activerecord-mysql2spatial-adapter'
gem 'require_all'
gem 'rspec'
gem 'rack-test'
gem 'pry'
gem 'database_cleaner'
gem 'simplecov'
gem 'factory_girl'
gem 'sidekiq'
gem 'rspec-sidekiq'
gem 'jiffybag', github: 'theodi/jiffybag'
gem 'unicorn'
gem 'raygun4ruby'
gem 'kaminari'
gem 'activesupport'
gem 'timecop'
gem 'iron_mq'
gem 'travis'
gem 'vcr'
gem 'webmock'
