ruby '2.1.3'
#ruby-gemset=ernest-marples

source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'mysql2'
gem 'activerecord-mysql2spatial-adapter'
gem 'require_all'
gem 'rspec'
gem 'rack-test'
gem 'pry'
gem 'database_cleaner'
gem 'simplecov'
gem 'factory_girl'
gem 'resque'
gem 'resque_spec'
gem 'dotenv'
gem 'unicorn'
gem 'raygun4ruby' 